# Generated by Django 2.2.8 on 2020-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_path',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
